import { type NextPage } from "next";
import { useState, Suspense } from "react";
import Head from "next/head";
import { Canvas } from "@react-three/fiber";

import Experience from "../components/Experience";
import { Loader } from "@react-three/drei";

const Experie: NextPage = () => {
  const [lep, setLep] = useState<boolean>(false);
  const [blen, setBlen] = useState<boolean>(false);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-full bg-black">
        <Canvas flat className="z-0">
          <color args={["#050505"]} attach="background" />
          <ambientLight />
          <directionalLight position={[150, 150, 150]} intensity={0.55} />
          <Experience setLep={setLep} lep={lep} blen={blen} setBlen={setBlen} />
        </Canvas>
        <Loader />
      </main>
    </>
  );
};

export default Experie;
