import { Loader } from "@react-three/drei";
import { type NextPage } from "next";

import Head from "next/head";
import { lazy, Suspense } from "react";
const MarkdownPreview = lazy(() => import("../components/Ex"));

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-full bg-black text-white">
        <Suspense fallback={<div className="text-white">Loading</div>}>
          <MarkdownPreview />
        </Suspense>
      </main>
    </>
  );
};

export default Home;
