import { type NextPage } from "next";
import Head from "next/head";

import { Canvas } from "@react-three/fiber";
import { Leva } from "leva";

import MainModel from "../components/MainModel";
import { useState } from "react";
import { createPortal } from "react-dom";
import Modal from "../components/UI/Modal";

const Home: NextPage = () => {
  const [showModal, setShowModal] = useState(false);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full">
        <div className="absolute z-20 text-white">
          <button onClick={() => setShowModal(true)}>
            Show modal using a portal
          </button>
          {showModal &&
            createPortal(
              <Modal onClose={() => setShowModal(false)} />,
              document.body
            )}
        </div>

        {/* Header */}
        <div className="absolute left-10 top-32 z-10 w-1/2">
          <div className="absolute left-0 ">
            <h1 className="bg-gradient-to-r from-orange-400 via-pink-500  to-pink-700 bg-clip-text text-7xl font-extrabold  uppercase text-transparent">
              Michal Nowotnik
            </h1>
            <h2 className="pl-3 text-lg uppercase text-white">
              Front-End Developer | 3D Designer
            </h2>
          </div>
        </div>
        <Leva />
        <Canvas flat className="z-0" onClick={() => setShowModal(false)}>
          <color args={["#000000"]} attach="background" />

          <MainModel />
        </Canvas>
      </main>
    </>
  );
};

export default Home;
