import { type NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import { Canvas } from "@react-three/fiber";
import { Leva } from "leva";

import { Perf } from "r3f-perf";
import MainContent from "../components/MainContent";
import Experience from "../components/Experience";

const Home: NextPage = () => {
  const [lep, setLep] = useState<boolean>(false);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full">
        {!lep && <MainContent />}
        <Leva collapsed />
        <Canvas flat className="z-0">
          <Perf />
          <ambientLight />
          <directionalLight position={[150, 150, 150]} intensity={0.55} />
          <color args={["#050505"]} attach="background" />
          <Experience setLep={setLep} lep={lep} />
        </Canvas>
      </main>
    </>
  );
};

export default Home;
